---
title: "Forest loss with raster data"
format: html
editor: visual
---


```{r}
# Load packages ---------------------------------------------------------
library(sf)
library(tidyverse)
library(terra) # Terra package is new version of library(raster) 
library(tmap)
library(leaflet)
```

## Data 

```{r}
## DATA DIRECTORY ---------------------------------------------------------
rootdir <- getwd() 
datadir <- path.expand("~/../../capstone/pyforest/data") #/
```


```{r}
# Chaco Region ----------------------------------------- ## BOUNDARY FILE ## 
department <- st_read(file.path(datadir, "Political_Boundaries", "departamento.shp")) 

chaco_dpto <- filter(department, nom_dpto %in% c("ALTO PARAGUAY", "PDTE. HAYES", "BOQUERON"))

chaco_region <- st_union(chaco_dpto, by_feature = FALSE, is_coverage = TRUE)|> st_make_valid()

# Convert chaco region to SpatialPolygons object
chaco_region_sp <- st_as_sf(chaco_region) %>% as("Spatial") # double check # 
chaco_region <- vect(chaco_region_sp) ## double check ##
```


```{r}
# Read in forest cover rasters ---------------------------------------------------------

# Need to figure out why it isn't reading in from new server tsosie is data connected to taylor? 

# 2000
  # Unzip rast manually
fc_2000 <- terra::rast(file.path(datadir, "fc_rast", "cf_rast_00.tif"))
  #plot(fc_2000)

# 2005 
fc_2005 <- terra::rast(file.path(datadir, "fc_rast", "cf_rast_05.tif"))

# 2011
fc_2011 <- terra::rast(file.path(datadir, "fc_rast", "cf_rast_11.tif"))

# 2013
fc_2013 <- terra::rast(file.path(datadir, "fc_rast", "cf_rast_13.tif"))

# 2015A
fc_2015 <- terra::rast(file.path(datadir, "fc_rast", "cf_rast_15a.tif"))
```

```{r}
# Raster data exploration -------------------------------------------------------------------------------------

# Histogram of raster values 
  # Confirms 1 = Forest Cover  
hist(fc_2005, maxpixels = 1000)


# Visual confirmation of 1 = Forest Cover
plot(fc_2000,col = "darkgreen")


# View in tmap interactive mode 
  # Downsample the raster to a lower resolution (not accurate but helps visualize)
r_down_00 <- aggregate(fc_2000, fact=5)
  # Plot the downsampled raster using tmap
tmap_mode("view")
tm_shape(r_down_00) + tm_raster(palette = "Greens") 
```



## 2000 - 2005 
```{r}
# Land Cover 2000 --------------------------------------------------------------------------------------------------

# Reclassify raster: 
  # 1 is forest cover (our rast has)
  # 0 is non forest cover 

# Reclassify NA's to 0 = non forest cover
fc_2000[is.na(fc_2000)] <- 0  # Now I have 0 & 1 value 
head(fc_2000) # Verify rast

# View rast with 0 & 1 
  # Define colors for each value
  mycolors <- c("red", "darkgreen")
  names(mycolors) <- c(0, 1)
  plot(fc_2000, col = mycolors) # We don't want the back so lets cut just to have our area of interest the chaco

# Chaco land cover 
lc_2000 <- terra::mask(fc_2000, chaco_region) # Chaco land cover 2000

# Verifying land cover rast 
plot(lc_2000, col = mycolors) # Visual check 
hist(lc_2000, maxpixels = 1000) # Verify new rast values
```

```{r}
# Land Cover 2005 --------------------------------------------------------------------------------------------------

fc_2005[is.na(fc_2005)] <- 0 
lc_2005 <- terra::mask(fc_2005, chaco_region) 

mycolors <- c("black", "dodgerblue") # Plot 2005 land cover
names(mycolors) <- c(0, 1)
plot(lc_2005, col = mycolors) 
```

```{r}
# 2000 - 2005 Forest Loss  ------------------------------------------------------------------------------------------
fl_00_05 <- lc_2005 - lc_2000 

# Verify new rast values 
  # -1 forest loss 
  # 0 forest
hist(fl_00_05, maxpixels = 1000)
plot(fl_00_05, col = mycolors) 
```


```{r}
# Visual verification of 2000 - 2005 forest loss  -------------------------------------------------------------------------
# These visuals lower the resolution to be able to map in tmap_mode("view"). They aren't accurate!

# Lowering the resoultion to map 
lc_00_down <- aggregate(lc_2000, fact=5) 
lc_05_down <- aggregate(lc_2005, fact=5)
fl_00_05_down <- aggregate(fl_00_05, fact=5)


# Mapping downsampled rasters
tmap_mode("view") 
tm_shape(lc_00_down) + tm_raster(palette = "Greens") + 
tm_shape(lc_05_down) + tm_raster(palette = "Blues") +
tm_shape(fl_00_05_down) + tm_raster(palette = "Reds") 
```




## 2005 - 2011
```{r}
# Land cover 2011 --------------------------------------------------------------------------------------------------
fc_2011[is.na(fc_2011)] <- 0  # Classifies non forest cover as 0 
lc_2011 <- terra::mask(fc_2011, chaco_region) # Cuts to only our area of interest the Chaco 
hist(lc_2011, maxpixels = 1000) # Verify rast values 
```

```{r}
# 2005 - 2011 Forest loss ------------------------------------------------------------------------------
fl_05_11 <- lc_2011 - lc_2005
hist(fl_00_05) # -1 loss forest 0 cover
```

#Note: Extents don't match Guillermo rewriting rasts to fix extents

## 2011 - 2013
```{r}

### MATCHING EXTENTS AND CALCULATIONS 
# Land cover 2013 --------------------------------------------------------------------------------------------------
fc_2013[is.na(fc_2013)] <- 0  
lc_2013 <- terra::mask(fc_2013, chaco_region) 
hist(lc_2013, maxpixels = 1000) 

# These land cover ext/dim don't match 
 terra::ext(lc_2011)
 terra::ext(lc_2013)
 dim(lc_2011)
 dim(lc_2013)

```



## 2013 - 2015 A 
```{r}
# Land cover 2015 --------------------------------------------------------------------------------------------------
fc_2015[is.na(fc_2015)] <- 0  # Classifies non forest cover as 0 
lc_2015 <- terra::mask(fc_2015, chaco_region) # Cuts to only our area of interest the Chaco 
hist(lc_2015, maxpixels = 1000) # Verify rast values 
```

# NEED TO COMPLETE 
## 2015 A - 2016 

## 2016 - 2017 

## 2017 - 2018

## 2018 - 2020 
