---
title: "Objective 1"
format: html
editor: visual
---

```{r}
### Loading libraries ------------------------------------------------------------------------
library(terra)
library(here)
library(dplyr)
library(sf)
library(rgdal)
library(tmap)
library(raster)

### Source in file to read in data ------------------------------------------------------------------------
source("read_in_data.R")
```

```{r}
### Chaco Area ------------------------------------------------------------------------

#Filter only the departments in the Chaco Region
chaco_dpto <- filter(department, nom_dpto %in% c("ALTO PARAGUAY", "PDTE. HAYES", "BOQUERON"))

# Calculate area of Chaco departments (hectares)
chaco_dpto <-dplyr::mutate(chaco_dpto, area = sf::st_area(chaco_dpto))|>
  mutate( area = as.numeric(area))|>
  mutate(area = area/10000)

# Visual check 
 # tm_shape(chaco_dpto)+
 #   tm_borders()+
 #   tm_text("nom_dpto", size = 1/2)

### Create 1 polygon for Chaco ------------------------------------------------------------------------
#Dissolve the Chaco Departament to get the interest area
chaco_region <- st_union(chaco_dpto, by_feature = FALSE, is_coverage = TRUE)|> st_make_valid()

#Convert sfc_POLYGON in to a SF
chaco_region <- st_sf(chaco_region) # st_sf makes df 

#Calculate area for all chaco (hectares)
chaco_region <-dplyr::mutate(chaco_region, area = sf::st_area(chaco_region))|>
  mutate(area = as.numeric(area))|>
  mutate(area = area/10000) # round(),2

# Visual Check 
# tm_shape(chaco_region)+
#   tm_borders()+
#   tm_text("area", size = 1)
```

```{r}
### Check CRS  ------------------------------------------------------------------------
st_crs(fc_2000) #'NA' so need to manually set
# st_crs(fc_2000) <- st_crs(32721) #doesn't work so set manually
st_crs(fc_2000) <- "+proj=utm +zone=21 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
st_crs(fc_2000)

st_crs(fc_2005) <- "+proj=utm +zone=21 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
st_crs(fc_2005)

st_crs(chaco_region) <- "+proj=utm +zone=21 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs" # VERFIY 
st_crs(chaco_region)
```

# 2000 FC

```{r}
# Double check CRS 
st_crs(dist_sub) # GOOD 
st_crs(fc_2000) # GOOD 

# FC 
fc_2000_chaco_subset <- st_intersection(dist_sub, fc_2000 )
```

# 2000 NF

```{r}
# Function 
st_erase = function(x, y) st_difference(x, st_union(st_combine(y)))

# NF
nf_2000_chaco_subset <- st_erase(dist_sub, fc_2000_chaco_subset)
```

# 2000 Maps

```{r}
#fc_2000_map 
  tmap_mode("view")
  tm_shape(fc_2000_chaco_subset) +
  tm_fill(col = "darkgreen") +
#fc_2005 
  tm_shape(nf_2005_chaco_subset) +
  tm_fill(col = "red")
```

# 2005 FC

```{r}
# Verify
st_crs(dist_sub)
st_crs(fc_2005) 

# FC
fc_2005_chaco_subset <- st_intersection(dist_sub, fc_2005)
```

# 2005 NF

```{r}
# Apply st_erase function we defined in 2000 NF

# NF 
nf_2005_chaco_subset <- st_erase(dist_sub, fc_2005_chaco_subset) 
```

```{r}
#fc_2005 
  tmap_mode("view")
  tm_shape(fc_2005_chaco_subset) +
  tm_fill(col = "dodgerblue") +
#nf_2005 
  tm_shape(nf_2005_chaco_subset) +
  tm_fill(col = "yellow")
```

# DF 2000 - 2005

```{r}
#st_erase = function(x, y) st_difference(x, st_union(st_combine(y)))

df <- st_erase(nf_2005_chaco_subset, nf_2000_chaco_subset)
```

# MAPS

```{r}
# fc_2000 
  tmap_mode("view") +
  tm_shape(fc_2000_chaco_subset) +
  tm_fill(col = "darkgreen") +
# nf_2000 
  tm_shape(nf_2000_chaco_subset) +
  tm_fill(col = "red") +
# fc_2005
  tm_shape(fc_2005_chaco_subset) +
  tm_fill(col = "dodgerblue") +
# nf_2005 
  tm_shape(nf_2005_chaco_subset) +
  tm_fill(col = "yellow") +
# 2000 - 2005 deforestation
  tm_shape(df) + 
  tm_fill(col = "blue")

# Save 2000 - 2005 deforestation file 
#write_sf(d, "00_05_lossforest.shp")
```
